# -*- coding: utf-8 -*-
# This script writes the complete clean POS.tsx
bt = chr(96)

template_lines = [
'import { useEffect, useState } from ' + bt + 'react' + bt + ';',
'import {',
'  IconDeviceDesktop, IconSearch, IconPlus, IconMinus,',
'  IconTrash, IconCurrencyRupee, IconCheck, IconX,',
'} from ' + bt + '@tabler/icons-react' + bt + ';',
"import api from '../services/api';",
"import type { Product } from '../types';",
'',
'interface CartItem {',
'  productId: number;',
'  name: string;',
'  salePrice: number;',
'  taxRate: number;',
'  quantity: number;',
'  total: number;',
'}',
'',
'export default function POS() {',
'  const [products, setProducts] = useState<Product[]>([]);',
'  const [cart, setCart] = useState<CartItem[]>([]);',
'  const [search, setSearch] = useState("");',
'  const [customerName, setCustomerName] = useState("");',
'  const [paymentMode, setPaymentMode] = useState<' + bt + 'cash' + bt + ' | ' + bt + 'upi' + bt + ' | ' + bt + 'card' + bt + '>(' + bt + 'cash' + bt + ');',
'  const [success, setSuccess] = useState(false);',
'  const [loading, setLoading] = useState(false);',
'',
'  useEffect(() => {',
'    api.get(' + bt + '/products' + bt + ', { params: { search, limit: 30 } })',
'    .then(r => setProducts(r.data.data ?? r.data))',
'    .catch(() => setProducts([]));',
'  }, [search]);',
'',
'  const addToCart = (p: Product) => {',
'    setCart(prev => {',
'      const existing = prev.find(i => i.productId === p.id);',
'      if (existing) {',
'        return prev.map(i => i.productId === p.id',
'          ? { ...i, quantity: i.quantity + 1, total: (i.quantity + 1) * i.salePrice }',
'          : i',
'        );',
'      }',
'      return [...prev, { productId: p.id, name: p.name, salePrice: p.salePrice, taxRate: p.taxRate, quantity: 1, total: p.salePrice }];',
'    });',
'  };',
'',
'  const updateQty = (productId: number, delta: number) => {',
'    setCart(prev => prev',
'      .map(i => i.productId === productId',
'        ? { ...i, quantity: i.quantity + delta, total: (i.quantity + delta) * i.salePrice }',
'        : i',
'      )',
'      .filter(i => i.quantity > 0)',
'    );',
'  };',
'',
'  const removeItem = (productId: number) =>',
'    setCart(prev => prev.filter(i => i.productId !== productId));',
'',
'  const subtotal = cart.reduce((s, i) => s + i.total, 0);',
'  const taxTotal = cart.reduce((s, i) => s + (i.total * i.taxRate / 100), 0);',
'  const grandTotal = subtotal + taxTotal;',
'',
'  const handleCheckout = async () => {',
'    if (cart.length === 0) return;',
'    setLoading(true);',
'    try {',
'      const res = await api.post(' + bt + '/pos/checkout' + bt + ', { customerName, paymentMode, items: cart, grandTotal });',
'      setSuccess(true);',
'      setCart([]);',
'      setCustomerName("");',
'      if (res.data && res.data.invoice && res.data.invoice.invoice_id) {',
'        window.open(' + bt + '/api/pos/receipt/${res.data.invoice.invoice_id}' + bt + `, '_blank');`,
'      }',
'      setTimeout(() => setSuccess(false), 3000);',
'    } catch { alert(' + bt + 'Checkout failed. Please try again.' + bt + '); }',
'    finally { setLoading(false); }',
'  };',
'',
'  return (',
'    <div>',
'      {/* Header */}',
'      <div className="flex items-center gap-3 mb-5">',
'        <div className="w-9 h-9 rounded-lg flex items-center justify-center" style={{ background: ' + bt + '#1a3480' + bt + ' }}>',
'          <IconDeviceDesktop size={20} color=' + bt + '#fff' + bt + ' />',
'        </div>',
'        <div>',
'          <h1 className="text-[20px] font-semibold text-gray-900">Point of Sale</h1>',
'          <p className="text-[12px] text-gray-400">Quick checkout and billing</p>',
'        </div>',
'      </div>',
'',
'      <div className="flex gap-4 h-[calc(100vh-180px)]">',
'        {/* LEFT - Product grid */}',
'        <div className="flex-1 flex flex-col gap-3 overflow-hidden">',
'          {/* Search */}',
'          <div className="flex items-center gap-2 bg-white border border-gray-200 rounded-xl px-3 h-[40px]">',
'            <IconSearch size={15} className="text-gray-400 flex-shrink-0" />',
'            <input',
'              type="text"',
'              placeholder="Search products or scan barcode..."',
'              value={search}',
'              onChange={e => setSearch(e.target.value)}',
'              className="outline-none border-none text-[13px] text-gray-700 placeholder:text-gray-400 w-full"',
'            />',
'          </div>',
'',
'          {/* Product cards */}',
'          <div className="overflow-y-auto flex-1">',
'            <div className="grid grid-cols-3 gap-2">',
'              {products.map(p => (',
'                <button',
'                  key={p.id}',
'                  onClick={() => addToCart(p)}',
'                  className={[' + bt,
'                    'bg-white border rounded-xl p-3 text-left transition-all hover:border-blue-300 hover:shadow-sm',
'                    p.stock === 0 ? ' + bt + 'opacity-40 cursor-not-allowed' + bt + ' : ' + bt + '' + bt + ',',
'                    cart.find(i => i.productId === p.id) ? ' + bt + 'border-blue-400 bg-blue-50' + bt + ' : ' + bt + 'border-gray-100' + bt + ',',
'                  ].join(' ')}',
'                  disabled={p.stock === 0}',
'                >',
'                  <div className="w-8 h-8 rounded-lg bg-blue-50 flex items-center justify-center mb-2">',
'                    <IconCurrencyRupee size={16} color=' + bt + '#1a3480' + bt + ' />',
'                  </div>',
'                  <p className="text-[12px] font-medium text-gray-800 leading-tight line-clamp-2">{p.name}</p>',
'                  <p className="text-[13px] font-semibold text-[#1a3480] mt-1">',
'                    ' + bt + '₹' + bt + '{p.salePrice.toLocaleString(' + bt + 'en-IN' + bt + ')}',
'                  </p>',
'                  <p className="text-[10px] text-gray-400 mt-0.5">',
'                    {p.stock > 0 ? ' + bt + 'Stock: ${p.stock}' + bt + ' : ' + bt + 'Out of stock' + bt + '}',
'                  </p>',
'                </button>',
'              ))}',
'              {products.length === 0 && (',
'                <div className="col-span-3 text-center py-12 text-gray-400 text-[13px]">',
'                  No products found',
'                </div>',
'              )}',
'            </div>',
'          </div>',
'        </div>',
'',
'        {/* RIGHT - Cart + Checkout */}',
'        <div className="w-[320px] flex flex-col bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden flex-shrink-0">',
'          {/* Cart header */}',
'          <div className="px-4 py-3 border-b border-gray-50 flex items-center justify-between">',
'            <h2 className="text-[14px] font-semibold text-gray-800">',
'              Cart <span className="text-[#1a3480]">({cart.length})</span>',
'            </h2>',
'            {cart.length > 0 && (',
'              <button onClick={() => setCart([])} className="text-[11px] text-red-500 hover:underline flex items-center gap-1">',
'                <IconX size={12} /> Clear',
'              </button>',
'            )}',
'          </div>',
'',
'          {/* Cart items */}',
'          <div className="flex-1 overflow-y-auto px-3 py-2 flex flex-col gap-2">',
'            {cart.length === 0 ? (',
'              <div className="flex flex-col items-center justify-center h-full text-gray-300 gap-2">',
'                <IconDeviceDesktop size={36} />',
'                <p className="text-[12px]">Add products to cart</p>',
'              </div>',
'            ) : (',
'              cart.map(item => (',
'                <div key={item.productId} className="bg-gray-50 rounded-lg px-3 py-2.5 flex items-center gap-2">',
'                  <div className="flex-1 min-w-0">',
'                    <p className="text-[12px] font-medium text-gray-800 truncate">{item.name}</p>',
'                    <p className="text-[11px] text-gray-400">',
'                      ' + bt + '₹' + bt + '{item.salePrice.toLocaleString(' + bt + 'en-IN' + bt + ')} each',
'                    </p>',
'                  </div>',
'                  <div className="flex items-center gap-1 flex-shrink-0">',
'                    <button onClick={() => updateQty(item.productId, -1)}',
'                      className="w-6 h-6 rounded border border-gray-200 flex items-center justify-center text-gray-500 hover:border-blue-300 hover:text-blue-600 transition-colors">',
'                      <IconMinus size={10} />',
'                    </button>',
'                    <span className="w-6 text-center text-[12px] font-semibold">{item.quantity}</span>',
'                    <button onClick={() => updateQty(item.productId, 1)}',
'                      className="w-6 h-6 rounded border border-gray-200 flex items-center justify-center text-gray-500 hover:border-blue-300 hover:text-blue-600 transition-colors">',
'                      <IconPlus size={10} />',
'                    </button>',
'                    <button onClick={() => removeItem(item.productId)}',
'                      className="w-6 h-6 rounded border border-red-100 flex items-center justify-center text-red-400 hover:bg-red-50 ml-1 transition-colors">',
'                      <IconTrash size={10} />',
'                    </button>',
'                  </div>',
'                </div>',
'              ))',
'            )}',
'          </div>',
'',
'          {/* Totals + Checkout */}',
'          <div className="border-t border-gray-100 px-4 py-3 flex flex-col gap-3">',
'            <input',
'              type="text"',
'              placeholder="Customer name (optional)"',
'              value={customerName}',
'              onChange={e => setCustomerName(e.target.value)}',
'              className="w-full border border-gray-200 rounded-lg px-3 h-[34px] text-[12px] outline-none focus:border-blue-300"',
'            />',
'',
'            <div className="flex gap-2">',
'              {(['cash','upi','card'] as const).map(mode => (',
'                <button',
'                  key={mode}',
'                  onClick={() => setPaymentMode(mode)}',
'                  className={[' + bt,
'                    'flex-1 py-1.5 rounded-lg text-[12px] font-medium border transition-all capitalize',',
'                    paymentMode === mode',
'                      ? ' + bt + 'bg-[#1a3480] text-white border-[#1a3480]' + bt + ' :',
'                      ' + bt + 'border-gray-200 text-gray-600 hover:border-gray-300' + bt + ',',
'                  ].join(' ')}',
'                >',
'                  {mode === ' + bt + 'upi' + bt + ' ? ' + bt + 'UPI' + bt + ' : mode.charAt(0).toUpperCase() + mode.slice(1)}',
'                </button>',
'              ))}',
'            </div>',
'',
'            <div className="bg-gray-50 rounded-lg px-3 py-2.5 flex flex-col gap-1.5">',
'              <div className="flex justify-between text-[12px] text-gray-500">',
'                <span>Subtotal</span>',
'                <span>' + bt + '₹' + bt + '{subtotal.toLocaleString(' + bt + 'en-IN' + bt + ', { minimumFractionDigits: 2 })}</span>',
'              </div>',
'              <div className="flex justify-between text-[12px] text-green-600">',
'                <span>Tax (GST)</span>',
'                <span>+' + bt + '₹' + bt + '{taxTotal.toLocaleString(' + bt + 'en-IN' + bt + ', { minimumFractionDigits: 2 })}</span>',
'              </div>',
'              <div className="flex justify-between text-[14px] font-bold text-gray-900 pt-1 border-t border-gray-200 mt-1">',
'                <span>Total</span>',
'                <span className="text-[#1a3480]">',
'                  ' + bt + '₹' + bt + '{grandTotal.toLocaleString(' + bt + 'en-IN' + bt + ', { minimumFractionDigits: 2 })}',
'                </span>',
'              </div>',
'            </div>',
'',
'            {success ? (',
'              <div className="flex items-center justify-center gap-2 py-2.5 rounded-lg bg-green-500 text-white text-[13px] font-semibold">',
'                <IconCheck size={16} /> Sale Complete!',
'              </div>',
'            ) : (',
'              <button',
'                onClick={handleCheckout}',
'                disabled={cart.length === 0 || loading}',
'                className="flex items-center justify-center gap-2 py-2.5 rounded-lg text-white text-[13px] font-semibold transition-colors disabled:opacity-40"',
'                style={{ background: ' + bt + '#1a3480' + bt + ' }}',
'              >',
'                {loading ? ' + bt + 'Processing...' + bt + ' : ' + bt + 'Checkout -- ₹${grandTotal.toLocaleString(' + bt + 'en-IN' + bt + ', { minimumFractionDigits: 2 })}' + bt + '}',
'              </button>',
'            )}',
'          </div>',
'        </div>',
'      </div>',
'    </div>',
'  );',
'}',
]

target_path = r'C:\Users\Admin\Desktop\Calude Test\erp-app\client\src\pages\POS.tsx'
with open(target_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(template_lines))

print('Wrote', len(template_lines), 'lines to POS.tsx')
# count total chars
import os
size = os.path.getsize(target_path)
print(f'File size: {size} bytes')
