import { Router } from 'express';
import { AuthRequest, requirePermission } from '../middleware/auth';
import { AmcAutomationService } from '../services/AmcAutomationService';

export const amcRouter = Router();
const amcService = new AmcAutomationService();

// ─── CONTRACTS ─────────────────────────────────────────────────────────────
amcRouter.post('/contracts', requirePermission('service:manage'), async (req: AuthRequest, res) => {
  try {
    const contract = await amcService.createContract(req.body, req.userId);
    res.status(201).json(contract);
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
});

amcRouter.get('/contracts', requirePermission('service:read'), async (req: AuthRequest, res) => {
  try {
    const list = await amcService.getContracts(req.query as any);
    res.json(list);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

amcRouter.get('/contracts/:id', requirePermission('service:read'), async (req: AuthRequest, res) => {
  try {
    const contract = await amcService.getContractById(Number(req.params.id));
    if (!contract) return res.status(404).json({ error: 'Contract not found' });
    res.json(contract);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

amcRouter.post('/contracts/:id/assets', requirePermission('service:manage'), async (req: AuthRequest, res) => {
  try {
    const asset = await amcService.addAsset({
      contract_id: Number(req.params.id),
      part_id: Number(req.body.part_id),
      device_name: req.body.device_name,
      serial_number: req.body.serial_number,
      service_interval_days: req.body.service_interval_days ? Number(req.body.service_interval_days) : undefined
    }, req.userId);
    res.status(201).json(asset);
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
});

// ─── AUTOMATION ENGINE ACTIONS ─────────────────────────────────────────────
amcRouter.post('/engine/auto-visits', requirePermission('service:manage'), async (req: AuthRequest, res) => {
  try {
    const jobs = await amcService.autoGenerateDueVisits(req.userId);
    res.json({ message: `Successfully generated ${jobs.length} due AMC service jobs.`, jobs });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

amcRouter.post('/engine/scan-missed', requirePermission('service:manage'), async (req: AuthRequest, res) => {
  try {
    const result = await amcService.scanMissedVisits(req.userId);
    res.json({ message: `Scanned and flagged ${result.missedCount} missed visits.`, count: result.missedCount });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

amcRouter.post('/engine/check-expiries', requirePermission('service:manage'), async (req: AuthRequest, res) => {
  try {
    const result = await amcService.checkContractExpiries(req.userId);
    res.json({ message: `Checked contracts: ${result.expiredCount} expired, ${result.warningCount} expiring soon.`, result });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

amcRouter.post('/contracts/:id/renew', requirePermission('service:manage'), async (req: AuthRequest, res) => {
  try {
    const quote = await amcService.generateRenewalQuotation(Number(req.params.id), req.userId!);
    res.status(201).json(quote);
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
});
