import { prisma } from '../index';
import { DocumentSeriesService } from './DocumentSeriesService';
import { BusinessEventService } from './BusinessEventService';
import { ServiceJobService } from './ServiceJobService';

const jobService = new ServiceJobService();

export class AmcAutomationService {
  // ─── CONTRACTS ───────────────────────────────────────────────────────────
  async createContract(data: {
    customer_id: number;
    start_date: Date;
    end_date: Date;
    billing_frequency: string; // ANNUAL, QUARTERLY
    annual_value: number;
  }, userId?: number) {
    const contract_number = await DocumentSeriesService.generateNextNumber('AmcContract');

    return prisma.$transaction(async (tx) => {
      const contract = await tx.amcContract.create({
        data: {
          contract_number,
          customer_id: data.customer_id,
          start_date: new Date(data.start_date),
          end_date: new Date(data.end_date),
          billing_frequency: data.billing_frequency,
          status: 'ACTIVE',
          annual_value: data.annual_value
        }
      });

      await BusinessEventService.logEvent({
        event_type: 'AMC_CONTRACT_CREATED',
        entity_type: 'AmcContract',
        entity_id: contract.contract_id,
        user_id: userId,
        description: `AMC Contract ${contract_number} created for customer #${data.customer_id}.`
      }, tx);

      return contract;
    });
  }

  async getContracts(query: { status?: string; customer_id?: number }) {
    const where: any = {};
    if (query.status) where.status = query.status;
    if (query.customer_id) where.customer_id = Number(query.customer_id);

    return prisma.amcContract.findMany({
      where,
      include: {
        customer: true,
        assets: { include: { part: true } },
        schedules: true
      },
      orderBy: { created_at: 'desc' }
    });
  }

  async getContractById(id: number) {
    return prisma.amcContract.findUnique({
      where: { contract_id: id },
      include: {
        customer: true,
        assets: { include: { part: true } },
        schedules: true
      }
    });
  }

  // ─── ASSETS ──────────────────────────────────────────────────────────────
  async addAsset(data: {
    contract_id: number;
    part_id: number;
    device_name: string;
    serial_number?: string;
    service_interval_days?: number;
  }, userId?: number) {
    return prisma.$transaction(async (tx) => {
      const contract = await tx.amcContract.findUnique({ where: { contract_id: data.contract_id } });
      if (!contract) throw new Error('AMC_CONTRACT_NOT_FOUND');

      const asset = await tx.amcAsset.create({
        data: {
          contract_id: data.contract_id,
          part_id: data.part_id,
          device_name: data.device_name,
          serial_number: data.serial_number || null,
          service_interval_days: data.service_interval_days || 90
        }
      });

      await BusinessEventService.logEvent({
        event_type: 'AMC_ASSET_ADDED',
        entity_type: 'AmcAsset',
        entity_id: asset.asset_id,
        user_id: userId,
        description: `Asset ${data.device_name} added to AMC Contract #${data.contract_id}.`
      }, tx);

      await this.generateVisitSchedulesForAsset(tx, asset, contract);

      return asset;
    });
  }

  private async generateVisitSchedulesForAsset(tx: any, asset: any, contract: any) {
    const start = new Date(contract.start_date);
    const end = new Date(contract.end_date);
    const intervalDays = asset.service_interval_days;

    const schedules = [];
    const currentPlanned = new Date(start);
    currentPlanned.setDate(currentPlanned.getDate() + intervalDays);

    while (currentPlanned <= end) {
      schedules.push({
        contract_id: contract.contract_id,
        asset_id: asset.asset_id,
        planned_date: new Date(currentPlanned),
        status: 'PLANNED'
      });
      currentPlanned.setDate(currentPlanned.getDate() + intervalDays);
    }

    if (schedules.length > 0) {
      await tx.amcVisitSchedule.createMany({
        data: schedules
      });
    }
  }

  // ─── AUTO VISIT GENERATION ───────────────────────────────────────────────
  async autoGenerateDueVisits(userId?: number) {
    // Find planned schedules in next 30 days that don't have service jobs yet
    const maxPlannedDate = new Date();
    maxPlannedDate.setDate(maxPlannedDate.getDate() + 30);

    const dueSchedules = await prisma.amcVisitSchedule.findMany({
      where: {
        status: 'PLANNED',
        planned_date: { lte: maxPlannedDate },
        service_job_id: null
      },
      include: {
        contract: true,
        asset: true
      }
    });

    const generatedJobs = [];

    for (const sched of dueSchedules) {
      // Create a service job in OPEN state for this AMC visit
      const job = await jobService.createServiceJob({
        customer_id: sched.contract.customer_id,
        job_type: 'AMC',
        problem_description: `Preventative AMC Maintenance for ${sched.asset ? sched.asset.device_name : 'AMC Asset'}`,
        items: sched.asset ? [
          {
            device_name: sched.asset.device_name,
            serial_number: sched.asset.serial_number || undefined,
            issue_description: 'Scheduled preventative maintenance'
          }
        ] : []
      }, userId);

      // Update schedule record with job link
      await prisma.amcVisitSchedule.update({
        where: { schedule_id: sched.schedule_id },
        data: { service_job_id: job.job_id }
      });

      // Automatically create a planned visit for this job on the schedule planned date
      const defaultTech = 1; // Default technician
      await jobService.scheduleVisit({
        job_id: job.job_id,
        technician_id: defaultTech,
        visit_date: sched.planned_date
      }, userId);

      generatedJobs.push(job);
    }

    return generatedJobs;
  }

  // ─── MISSED VISIT DETECTION ──────────────────────────────────────────────
  async scanMissedVisits(userId?: number) {
    const now = new Date();

    // Find planned visit schedules whose planned date has passed, and which don't have executed visits
    const overdueSchedules = await prisma.amcVisitSchedule.findMany({
      where: {
        status: 'PLANNED',
        planned_date: { lt: now }
      },
      include: {
        contract: true,
        asset: true
      }
    });

    let missedCount = 0;

    for (const sched of overdueSchedules) {
      let isMissed = false;
      
      if (!sched.service_job_id) {
        isMissed = true;
      } else {
        // Check if there are any executed visits for the linked service job
        const visits = await prisma.serviceVisit.findMany({
          where: { job_id: sched.service_job_id }
        });
        const hasExecuted = visits.some(v => v.status === 'EXECUTED');
        if (!hasExecuted) {
          isMissed = true;
        }
      }

      if (isMissed) {
        // Transition schedule status to MISSED
        await prisma.amcVisitSchedule.update({
          where: { schedule_id: sched.schedule_id },
          data: { status: 'MISSED' }
        });

        // Log business event for missed visit escalation
        await BusinessEventService.logEvent({
          event_type: 'AMC_VISIT_MISSED',
          entity_type: 'AmcVisitSchedule',
          entity_id: sched.schedule_id,
          user_id: userId,
          description: `AMC preventative visit scheduled for ${sched.planned_date.toDateString()} was MISSED for contract ${sched.contract.contract_number}.`
        });

        missedCount++;
      }
    }

    return { missedCount };
  }

  // ─── EXPIRY MONITORING ───────────────────────────────────────────────────
  async checkContractExpiries(userId?: number) {
    const now = new Date();
    
    // 1. Mark expired contracts
    const activeContracts = await prisma.amcContract.findMany({
      where: { status: 'ACTIVE' }
    });

    let expiredCount = 0;
    let warningCount = 0;

    const warningHorizon = new Date();
    warningHorizon.setDate(warningHorizon.getDate() + 30);

    for (const contract of activeContracts) {
      if (contract.end_date < now) {
        // Transition to EXPIRED
        await prisma.amcContract.update({
          where: { contract_id: contract.contract_id },
          data: { status: 'EXPIRED' }
        });

        await BusinessEventService.logEvent({
          event_type: 'AMC_CONTRACT_EXPIRED',
          entity_type: 'AmcContract',
          entity_id: contract.contract_id,
          user_id: userId,
          description: `AMC Contract ${contract.contract_number} has EXPIRED on ${contract.end_date.toDateString()}.`
        });

        expiredCount++;
      } else if (contract.end_date <= warningHorizon) {
        // Log warning event if expiring in next 30 days
        await BusinessEventService.logEvent({
          event_type: 'AMC_CONTRACT_EXPIRING',
          entity_type: 'AmcContract',
          entity_id: contract.contract_id,
          user_id: userId,
          description: `AMC Contract ${contract.contract_number} is expiring soon on ${contract.end_date.toDateString()}.`
        });

        warningCount++;
      }
    }

    return { expiredCount, warningCount };
  }

  // ─── RENEWAL QUOTE GENERATION ────────────────────────────────────────────
  async generateRenewalQuotation(contractId: number, userId: number) {
    return prisma.$transaction(async (tx) => {
      const contract = await tx.amcContract.findUnique({
        where: { contract_id: contractId },
        include: { customer: true, assets: true }
      });
      if (!contract) throw new Error('AMC_CONTRACT_NOT_FOUND');

      const quote_number = await DocumentSeriesService.generateNextNumber('Quotation');

      // Use annual contract value divided across parts/assets or simple lump sum
      const subtotal = Number(contract.annual_value);
      const total_discount = 0;
      const total_tax = subtotal * 0.18; // 18% GST default
      const total_amount = subtotal + total_tax;

      const valid_until = new Date();
      valid_until.setDate(valid_until.getDate() + 30); // 30 days validity

      // Create a quotation
      const quote = await tx.quotation.create({
        data: {
          quote_number,
          customer_id: contract.customer_id,
          quote_date: new Date(),
          valid_until,
          status: 'draft',
          subtotal,
          total_discount,
          total_tax,
          total_amount,
          terms: 'Standard AMC Renewal terms apply.',
          notes: `Auto-generated renewal proposal for contract ${contract.contract_number}.`,
          created_by: userId
        }
      });

      // Update contract status to PENDING_RENEWAL
      await tx.amcContract.update({
        where: { contract_id: contractId },
        data: { status: 'PENDING_RENEWAL' }
      });

      await BusinessEventService.logEvent({
        event_type: 'AMC_RENEWAL_QUOTE_GENERATED',
        entity_type: 'AmcContract',
        entity_id: contractId,
        user_id: userId,
        description: `Renewal Quotation ${quote_number} generated for contract ${contract.contract_number}.`
      }, tx);

      return quote;
    });
  }
}
