module.exports = {
  repairs: require('./repairs'),
  customers: require('./customers'),
  parts: require('./parts'),
  sales: require('./sales'),
  invoices: require('./invoices'),
  quotations: require('./quotations'),
  purchases: require('./purchases'),
  deliveryChallans: require('./deliveryChallans'),
  technicians: require('./technicians'),
  suppliers: require('./suppliers'),
  locations: require('./locations'),
  users: require('./users'),
  settings: require('./settings'),
  reports: require('./reports'),
  search: require('./search'),
  pos: require('./pos'),
  auth: require('./auth'),
  crm: require('./crm'),
  accounting: require('./accounting'),
payroll: require('./payroll'),
companies: require('./companies'),
audit: require('./audit'),
stores: require('./stores'),
print: require('./print')
};